@echo on
REM Auto-generated by CMake configure. Uses relative paths from script directory.

taskkill /f /im PdfWinViewer.exe /t >nul 2>&1
call "C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\Tools\VsDevCmd.bat" -arch=amd64 -host_arch=amd64
if errorlevel 1 exit /b 1

set PROJ="%~dp0build\PdfWinViewer.vcxproj"
set OUTEXE="%~dp0build\Debug\PdfWinViewer.exe"

msbuild %PROJ% /m /p:Configuration=Debug /p:Platform=x64 /t:Build /nologo /v:minimal
if exist %OUTEXE% (
  echo BUILD OK
) else (
  echo BUILD FAILED
  exit /b 1
)


